import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";
import { COLORS, SHADOWS, BORDER_RADIUS } from "../../helper/theme";

const evidenceSharedStyles = StyleSheet.create({
    backgroundImage: {
        position: 'absolute',
        left: 0,
        top: 0,
        width: Dimensions.get('window').width,
        height: Dimensions.get('window').height,
    },
    mainContainer: {
        flex: 1,
        width: "100%",
        paddingTop: 40,
        paddingLeft: 20,
        paddingRight: 20,
        opacity: 1,
        backgroundColor: COLORS.overlayDark,
    },
    navigationBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    backButton: {
        color: COLORS.white,
        opacity: 0.9,
        fontSize: 16,
        fontWeight: '600',
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: BORDER_RADIUS.round,
    },
    continueHeaderButton: {
        color: COLORS.white,
        opacity: 0.9,
        fontSize: 16,
        fontWeight: '600',
        backgroundColor: '#10B981', // Emerald green
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: BORDER_RADIUS.round,
    },
    title: {
        color: COLORS.white,
        paddingBottom: 15,
        paddingTop: 15,
        fontSize: 32,
        fontWeight: "800",
        textAlign: "center",
        letterSpacing: 0.5,
    },
    picture: {
        width: "100%",
        height: 180,
        borderRadius: BORDER_RADIUS.large,
        marginVertical: 10,
    },
    dropdownContainer: {
        marginTop: 15,
        padding: 15,
        backgroundColor: COLORS.glassLight,
        borderRadius: BORDER_RADIUS.large,
        ...SHADOWS.medium,
    },
    dropdownLabel: {
        fontSize: 15,
        fontWeight: '700',
        color: COLORS.textMedium,
        marginBottom: 6,
    },
    picker: {
        backgroundColor: '#F1F5F9',
        borderRadius: BORDER_RADIUS.medium,
        width: '100%',
        marginBottom: 16,
        color: COLORS.textDark,
    },
    finalizeButton: {
        paddingVertical: 14,
        borderRadius: BORDER_RADIUS.large,
        alignItems: 'center',
        backgroundColor: COLORS.primary,
        width: "100%",
        ...SHADOWS.medium,
    },
    buttonText: {
        color: COLORS.white,
        fontSize: 18,
        fontWeight: '700',
    },
    dateTimeContainer: {
        backgroundColor: COLORS.glassLight,
        borderRadius: BORDER_RADIUS.large,
        padding: 15,
        marginBottom: 16,
        ...SHADOWS.light,
    },
    dateTimeText: {
        color: COLORS.textDark,
        fontSize: 16,
        fontWeight: '600',
    },
    textInput: {
        backgroundColor: COLORS.glassLight,
        borderRadius: BORDER_RADIUS.large,
        width: '100%',
        marginBottom: 16,
        fontSize: 16,
        padding: 15,
        color: COLORS.textDark,
        minHeight: 100,
        textAlignVertical: 'top',
        ...SHADOWS.light,
    },
    imageContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 10,
        marginBottom: 15,
    },
    imageWrapper: {
        width: '30%',
        margin: '1.5%',
        aspectRatio: 1,
        borderRadius: BORDER_RADIUS.medium,
        overflow: 'hidden',
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    image: {
        width: '100%',
        height: '100%',
    },
    removeImageButton: {
        position: 'absolute',
        top: 4,
        right: 4,
        backgroundColor: COLORS.danger,
        borderRadius: BORDER_RADIUS.round,
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
        ...SHADOWS.light,
    },
    removeImageText: {
        color: COLORS.white,
        fontSize: 14,
        fontWeight: 'bold',
    },
    addImageButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: BORDER_RADIUS.medium,
        width: '30%',
        margin: '1.5%',
        aspectRatio: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: 'rgba(255, 255, 255, 0.6)',
        borderStyle: 'dashed',
    },
    addImageText: {
        color: COLORS.white,
        fontSize: 28,
        fontWeight: 'bold',
    },
});

export default evidenceSharedStyles;
