import { Platform, StyleSheet } from 'react-native';

// Palette for the Voice Agent prototype — dark, high-contrast, glanceable from a
// few feet away (matches the design doc mockups).
export const VC = {
    bg: '#0B0F10',
    surface: '#161B1D',
    surfaceRaised: '#1E2528',
    border: '#2A3437',
    accent: '#2DD4BF',        // teal — listening / agent
    accentDim: 'rgba(45, 212, 191, 0.15)',
    accentBorder: 'rgba(45, 212, 191, 0.55)',
    number: '#3B82F6',        // blue chips for the numbered index
    text: '#F1F5F9',
    textDim: '#94A3B8',
    textFaint: '#64748B',
    danger: '#F87171',
};

export default StyleSheet.create({
    safe: { flex: 1, backgroundColor: VC.bg },
    container: { flex: 1, backgroundColor: VC.bg },
    scroll: { padding: 20, paddingBottom: 28 },

    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 4,
    },
    topBarBtn: {
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 999,
        backgroundColor: VC.surface,
        borderWidth: 1,
        borderColor: VC.border,
    },
    topBarBtnText: { color: VC.textDim, fontSize: 14, fontWeight: '600' },

    stepPill: {
        alignSelf: 'center',
        backgroundColor: VC.surface,
        borderRadius: 999,
        paddingVertical: 7,
        paddingHorizontal: 16,
        marginBottom: 14,
    },
    stepPillText: {
        color: VC.textDim,
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 1.5,
    },

    question: {
        color: VC.text,
        fontSize: 30,
        lineHeight: 36,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 18,
    },

    listenWrap: { alignItems: 'center', marginBottom: 14 },
    listenRing: {
        width: 96,
        height: 96,
        borderRadius: 999,
        borderWidth: 2,
        borderColor: VC.accentBorder,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: VC.accentDim,
    },
    listenBars: { flexDirection: 'row', alignItems: 'center', height: 34 },
    bar: {
        width: 5,
        marginHorizontal: 2,
        borderRadius: 3,
        backgroundColor: VC.accent,
    },
    listenLabel: {
        color: VC.accent,
        fontSize: 16,
        fontWeight: '700',
        marginTop: 10,
    },
    idleLabel: { color: VC.textFaint },

    transcriptCard: {
        backgroundColor: VC.surface,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: VC.border,
        paddingVertical: 16,
        paddingHorizontal: 18,
        marginBottom: 10,
    },
    transcriptText: { color: VC.text, fontSize: 18, fontWeight: '500' },
    transcriptPlaceholder: { color: VC.textFaint, fontSize: 16, fontStyle: 'italic' },

    agentLine: {
        color: VC.accent,
        fontSize: 15,
        lineHeight: 21,
        fontWeight: '600',
        marginBottom: 16,
        paddingHorizontal: 4,
    },

    optionsWrap: { marginTop: 2 },
    optionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    chip: {
        backgroundColor: VC.surface,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: VC.border,
        paddingVertical: 14,
        paddingHorizontal: 14,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'center',
    },
    chipFull: { width: '100%' },
    chipHalf: { width: '48%' },
    chipActive: {
        backgroundColor: VC.accentDim,
        borderColor: VC.accentBorder,
    },
    chipIndex: {
        width: 26,
        height: 26,
        borderRadius: 999,
        backgroundColor: VC.number,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    chipIndexText: { color: '#fff', fontSize: 13, fontWeight: '800' },
    chipLabel: { color: VC.text, fontSize: 16, fontWeight: '700', flexShrink: 1 },
    chipConfirm: { color: VC.accent, fontWeight: '800' },

    weightReadout: {
        backgroundColor: VC.surface,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: VC.border,
        paddingVertical: 22,
        alignItems: 'center',
        marginBottom: 14,
    },
    weightValue: { color: VC.accent, fontSize: 44, fontWeight: '900' },
    weightUnitLabel: {
        color: VC.textDim,
        fontSize: 13,
        fontWeight: '800',
        letterSpacing: 2,
        marginTop: 2,
    },
    primaryBtn: {
        backgroundColor: VC.accentDim,
        borderWidth: 1,
        borderColor: VC.accentBorder,
        borderRadius: 14,
        paddingVertical: 16,
        alignItems: 'center',
        marginBottom: 12,
    },
    primaryBtnText: { color: VC.text, fontSize: 17, fontWeight: '800' },

    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: VC.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: VC.border,
        paddingVertical: 14,
        paddingHorizontal: 16,
        marginBottom: 8,
    },
    summaryLabel: { color: VC.text, fontSize: 16, fontWeight: '700' },
    summaryWeight: { color: VC.accent, fontSize: 16, fontWeight: '800' },
    summaryTotal: {
        color: VC.textDim,
        fontSize: 14,
        fontWeight: '800',
        textAlign: 'center',
        marginVertical: 10,
    },

    hint: {
        color: VC.textFaint,
        fontSize: 12,
        textAlign: 'center',
        marginTop: 6,
        lineHeight: 18,
    },

    inputBar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingTop: 10,
        paddingBottom: 16,
        borderTopWidth: 1,
        borderTopColor: VC.border,
        backgroundColor: VC.surface,
    },
    input: {
        flex: 1,
        backgroundColor: VC.surfaceRaised,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: VC.border,
        paddingVertical: 12,
        paddingHorizontal: 18,
        color: VC.text,
        fontSize: 15,
    },
    micBtn: {
        width: 46,
        height: 46,
        borderRadius: 999,
        backgroundColor: VC.accent,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 10,
    },
    micBtnGhost: {
        backgroundColor: VC.surfaceRaised,
        borderWidth: 1,
        borderColor: VC.accentBorder,
        marginLeft: 0,
        marginRight: 10,
    },
    micBtnLive: {
        backgroundColor: VC.danger,
        borderColor: VC.danger,
    },
    micBtnText: { fontSize: 18 },
    voiceError: {
        color: VC.danger,
        fontSize: 13,
        fontWeight: '600',
        marginTop: 8,
        textAlign: 'center',
    },
    voiceStatus: {
        alignSelf: 'stretch',
        backgroundColor: VC.surface,
        borderWidth: 1,
        borderColor: VC.border,
        borderRadius: 12,
        paddingVertical: 9,
        paddingHorizontal: 14,
        marginBottom: 10,
    },
    voiceStatusLive: {
        backgroundColor: VC.accentDim,
        borderColor: VC.accentBorder,
    },
    voiceStatusWarn: {
        backgroundColor: 'rgba(248, 113, 113, 0.12)',
        borderColor: VC.danger,
    },
    voiceStatusText: {
        color: VC.text,
        fontSize: 13,
        fontWeight: '700',
        textAlign: 'center',
    },
    voiceDebug: {
        color: VC.textFaint,
        fontSize: 10.5,
        textAlign: 'center',
        marginBottom: 8,
        fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },
    diagBox: {
        backgroundColor: '#0E1416',
        borderWidth: 1,
        borderColor: VC.border,
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
    },
    diagLine: {
        color: VC.accent,
        fontSize: 10.5,
        marginBottom: 5,
        fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },
    diagEvent: {
        color: VC.textDim,
        fontSize: 10.5,
        lineHeight: 15,
        fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    },

    // Wake screen
    wakeWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
    wakeTitle: {
        color: VC.text,
        fontSize: 26,
        fontWeight: '900',
        textAlign: 'center',
        marginBottom: 8,
    },
    wakeSub: { color: VC.textDim, fontSize: 15, textAlign: 'center', marginBottom: 34, lineHeight: 22 },
    wakeMic: {
        width: 130,
        height: 130,
        borderRadius: 999,
        backgroundColor: VC.accentDim,
        borderWidth: 2,
        borderColor: VC.accentBorder,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 22,
    },
    wakeMicActive: { backgroundColor: 'rgba(248, 113, 113, 0.18)', borderColor: VC.danger },
    wakeMicIcon: { fontSize: 52 },
    wakeHint: { color: VC.textFaint, fontSize: 13, textAlign: 'center', marginTop: 8 },
    wakeContext: {
        color: VC.textDim,
        fontSize: 13,
        textAlign: 'center',
        marginTop: 26,
        backgroundColor: VC.surface,
        borderRadius: 999,
        paddingVertical: 8,
        paddingHorizontal: 16,
        overflow: 'hidden',
    },

    doneWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
    doneIcon: { fontSize: 64, marginBottom: 16 },
    doneTitle: { color: VC.text, fontSize: 24, fontWeight: '900', marginBottom: 8, textAlign: 'center' },
    doneSub: { color: VC.textDim, fontSize: 15, textAlign: 'center', marginBottom: 28 },
});
